/*
    This file is part of JFLICKS.

    JFLICKS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    JFLICKS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with JFLICKS.  If not, see <http://www.gnu.org/licenses/>.
*/
package org.jflicks.metadata;

/**
 * A search should return one or more Hit objects.
 *
 * @author Doug Barnum
 * @version 1.0
 */
public class Hit {

    private String id;
    private String metadataTitle;
    private String title;
    private String description;
    private String bannerURL;
    private String posterURL;
    private String fanartURL;
    private String released;

    /**
     * Simple empty constructor.
     */
    public Hit() {
    }

    /**
     * A unique ID is associated with this object.
     *
     * @return An ID value as a String.
     */
    public String getId() {
        return (id);
    }

    /**
     * A unique ID is associated with this object.
     *
     * @param s An ID value as a String.
     */
    public void setId(String s) {
        id = s;
    }

    /**
     * This Hit was generated by a metadata title.
     *
     * @return A String instance.
     */
    public String getMetadataTitle() {
        return (metadataTitle);
    }

    /**
     * This Hit was generated by a metadata title.
     *
     * @param s A String instance.
     */
    public void setMetadataTitle(String s) {
        metadataTitle = s;
    }

    /**
     * There is a Title property.
     *
     * @return The title.
     */
    public String getTitle() {
        return (title);
    }

    /**
     * There is a Title property.
     *
     * @param s The title.
     */
    public void setTitle(String s) {
        title = s;
    }

    /**
     * A description of the recording.
     *
     * @return The description as a String instance.
     */
    public String getDescription() {
        return (description);
    }

    /**
     * A description of the recording.
     *
     * @param s The description as a String instance.
     */
    public void setDescription(String s) {
        description = s;
    }

    /**
     * URL as a String where a banner image can be found if it exists.
     *
     * @return A String instance.
     */
    public String getBannerURL() {
        return (bannerURL);
    }

    /**
     * URL as a String where a banner image can be found if it exists.
     *
     * @param s A String instance.
     */
    public void setBannerURL(String s) {
        bannerURL = s;
    }

    /**
     * URL as a String where a poster image can be found if it exists.
     *
     * @return A String instance.
     */
    public String getPosterURL() {
        return (posterURL);
    }

    /**
     * URL as a String where a poster image can be found if it exists.
     *
     * @param s A String instance.
     */
    public void setPosterURL(String s) {
        posterURL = s;
    }

    /**
     * URL as a String where a fanart image can be found if it exists.
     *
     * @return A String instance.
     */
    public String getFanartURL() {
        return (fanartURL);
    }

    /**
     * URL as a String where a fanart image can be found if it exists.
     *
     * @param s A String instance.
     */
    public void setFanartURL(String s) {
        fanartURL = s;
    }

    /**
     * When the Video was released.
     *
     * @return A String instance.
     */
    public String getReleased() {
        return (released);
    }

    /**
     * When the Video was released.
     *
     * @param s A String instance.
     */
    public void setReleased(String s) {
        released = s;
    }

}

